name: Deploy using AWS SSM Send-Command

on:
  push:
    branches: [ main ]

jobs:
 start:
  runs-on: ubuntu-latest 

  steps:
  - uses: actions/checkout@v2
  - run: echo secrets.AWS_ACCESS_KEY_ID sample key

  - name: AWS SSM Send-Command
    uses: peterkimzz/aws-ssm-send-command@v1.1.1
    id: ssm

    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      aws-region: ap-south-1
      instance-ids: ${{ secrets.INSTANCE_ID}}
